default: &default
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  database: Overtime_development
  host: localhost
  username: <%= ENV.fetch("DB_USERNAME") %>
  password: <%= ENV.fetch("DB_PASSWORD") %>
  port: 5432

test:
  <<: *default
  database: Overtime_test
  host: localhost
  username: <%= ENV.fetch("DB_USERNAME") %>
  password: <%= ENV.fetch("DB_PASSWORD") %>
  port: 5432


production:
  <<: *default
  database: Overtime_production
  username: Overtime
  password: <%= ENV['OVERTIME_DATABASE_PASSWORD'] %>
